print("Hey there!", "What's your name?")
varname = str(input())
print("Hey," , varname, sep = ' ')
print("I have a Maths Test tomorrow and I'm really scared.")
print("How about we solve some equations, so I can practice?")
print("Let's start with the area of a trapezium.", "Enter the measure of the first base.")
vartrside1 = int(input())
print("Okay, now enter the second base")
vartrside2 = int(input())
print("Awesome, and the height?")
vartrheight = int(input())
vartrarea = (vartrside1+vartrside2)/2 * vartrheight
print("As the formula goes:")
print("Area of a trapezium = a + b/2 x h")
print("So, the answer is:")
print(vartrarea)
print("Next, let's do the area of a cube")
print("What's the side of the cube?")
varcuside = int(input())
varcuarea = 6*varcuside*varcuside
print("Okay, so as the formula goes:")
print("Area of a cube = 6a²")
print("So, the area of a cube of side"+ varcuside + "is:")
print(varcuarea)

